namespace GardenHose.Game.GameAssetManager;

internal enum GHGameAnimationName
{
    Special_SinglePixel,

    Planet_Atmosphere_Default,
    Planet_GasSurface_1,
    Planet_GasOverlay_1,
    Planet_GasOverlay_2,
    Planet_RockSurface_1,
    Planet_WaterSurface_1,
    Planet_Clouds_1,
    Planet_Clouds_2,
    Planet_Clouds_3,
    Planet_Clouds_4,
    Planet_Clouds_5,

    Particle_Test,

    Particle_Fuel1,
    Particle_Fuel2,
    Particle_Fuel3,
    Particle_Fuel4,

    Background_Default,
    Background_Star_Small,
    Background_Star_Medium,
    Background_Star_Big,

    Ship_Probe_Base,
    Ship_Probe_Head,
    Ship_Probe_SideThruster,
    Ship_Probe_MainThruster,
    Ship_Probe_RollPanel,
    Ship_Probe_RollGlass,
    Ship_Probe_RollDisplay,
    Ship_Probe_RollIndicator,
    Ship_Probe_RollIndicatorShadow,
    Ship_Probe_ErrorPanel,
    Ship_Probe_ErrorGlass,
    Ship_Probe_ErrorLT,
    Ship_Probe_ErrorMT,
    Ship_Probe_ErrorRT,
    Ship_Probe_ErrorOxygen,
    Ship_Probe_ErrorSpin,
    Ship_Probe_ErrorLeak,
    Ship_Probe_ErrorFuel,
    Ship_Probe_Meter,
    Ship_Probe_MeterIndicator,
    Ship_Probe_MeterMarkingA,
    Ship_Probe_MeterMarkingS,
    Ship_Probe_ThrusterPanel,
    Ship_Probe_ThrusterPanelLightPanel,
    Ship_Probe_ThrusterPanelLightDisplay,
    Ship_Probe_ThrusterPanelLightGlass,
    Ship_Probe_ThrusterPanelLightPanelShadow,
    Ship_Probe_ThrusterPanelSwitchPanel,
    Ship_Probe_ThrusterPanelSwitchPanelShadow,
    Ship_Probe_ThrusterPanelSwitch,
    Ship_Probe_ThrusterPanelSwitchShadow,
    Ship_Probe_PowerPanel,
    Ship_Probe_PowerButton,
    Ship_Probe_PowerButtonShadow,
    Ship_Probe_AutopilotPanel,
    Ship_Probe_AutopilotKnob,
    Ship_Probe_FuelGaugePanel,
    Ship_Probe_FuelGaugeGlass,
    Ship_Probe_FuelGaugeIndicatorTop,
    Ship_Probe_FuelGaugeIndicatorBottom,
    Ship_Probe_FuelGaugeIndicatorShadowTop,
    Ship_Probe_FuelGaugeIndicatorShadowBottom,
}